### ISSUE TITLE
Certain items don’t drop

### ISSUE THREAD

**Issue by duncanwebb** [jglrxavpok/Moar-Boats#59] opened 2018-11-20 13:30 UTC
Rudders, note blocks, diving bells and ropes disappear when dropped or breaking the boat. 

I’m wondering if this is by design.

**Comment by jglrxavpok** [comment] 2018-11-20 13:37
It is not by design, I simply forgot to add the drops...
will do in the next release!

**Comment by jglrxavpok** [comment] 2018-11-20 22:07
Fixed in https://github.com/jglrxavpok/Moar-Boats/commit/1f042eca8d092adcbb40bfd59f15e8380384e24d

**Closed by jglrxavpok** 2018-11-20 22:07 UTC
